namespace Sounds
{
    public enum SoundType
    {
        Forest,
        MiniGame,
        InsideForgery,
        OpenDoor,
        CloseDoor,
        GarbageThrow,
        ActionButtonClick,
        PlayerStepOutside,
        PlayerStepInside,
        CustomerStep,
        UiButton,
        Interact,
        Success,
        Water,
        SeatToggle,
        BucketGeneration,
        BucketTake,
        PotionToggle,
        BookToggle,
        BookPage,
        SphereToggle,
        CharacterPrinted,
        LeverToggle,
        MagicEngineStartup,
        MagicConverter,
        Feather,    
        MagicEngineIdle,
        EngineManaRestore,
        EngineWaterRestore,
        MainMenu
    }
}